version: "3.8"
services:
  devenv:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - LOCAL_UID=${UID}
        - LOCAL_GID=${GID}
    container_name: devenv
    volumes:
      - ../../:/work
    working_dir: /work
