version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: daily
