// <auto-generated/>
#nullable enable

namespace Omnius.Lxna.Components.Internal.Models
{
    internal sealed partial class FileMeta : global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Lxna.Components.Internal.Models.FileMeta>
    {
        public static global::Omnius.Core.RocketPack.IRocketPackObjectFormatter<global::Omnius.Lxna.Components.Internal.Models.FileMeta> Formatter => global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Lxna.Components.Internal.Models.FileMeta>.Formatter;
        public static global::Omnius.Lxna.Components.Internal.Models.FileMeta Empty => global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Lxna.Components.Internal.Models.FileMeta>.Empty;

        static FileMeta()
        {
            global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Lxna.Components.Internal.Models.FileMeta>.Formatter = new ___CustomFormatter();
            global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Lxna.Components.Internal.Models.FileMeta>.Empty = new global::Omnius.Lxna.Components.Internal.Models.FileMeta(global::Omnius.Lxna.Components.Models.NestedPath.Empty, 0, global::Omnius.Core.RocketPack.Timestamp.Zero);
        }

        private readonly global::System.Lazy<int> ___hashCode;

        public FileMeta(global::Omnius.Lxna.Components.Models.NestedPath path, ulong length, global::Omnius.Core.RocketPack.Timestamp lastWriteTime)
        {
            if (path is null) throw new global::System.ArgumentNullException("path");
            this.Path = path;
            this.Length = length;
            this.LastWriteTime = lastWriteTime;

            ___hashCode = new global::System.Lazy<int>(() =>
            {
                var ___h = new global::System.HashCode();
                if (path != default) ___h.Add(path.GetHashCode());
                if (length != default) ___h.Add(length.GetHashCode());
                if (lastWriteTime != default) ___h.Add(lastWriteTime.GetHashCode());
                return ___h.ToHashCode();
            });
        }

        public global::Omnius.Lxna.Components.Models.NestedPath Path { get; }
        public ulong Length { get; }
        public global::Omnius.Core.RocketPack.Timestamp LastWriteTime { get; }

        public static global::Omnius.Lxna.Components.Internal.Models.FileMeta Import(global::System.Buffers.ReadOnlySequence<byte> sequence, global::Omnius.Core.IBytesPool bytesPool)
        {
            var reader = new global::Omnius.Core.RocketPack.RocketPackObjectReader(sequence, bytesPool);
            return Formatter.Deserialize(ref reader, 0);
        }
        public void Export(global::System.Buffers.IBufferWriter<byte> bufferWriter, global::Omnius.Core.IBytesPool bytesPool)
        {
            var writer = new global::Omnius.Core.RocketPack.RocketPackObjectWriter(bufferWriter, bytesPool);
            Formatter.Serialize(ref writer, this, 0);
        }

        public static bool operator ==(global::Omnius.Lxna.Components.Internal.Models.FileMeta? left, global::Omnius.Lxna.Components.Internal.Models.FileMeta? right)
        {
            return (right is null) ? (left is null) : right.Equals(left);
        }
        public static bool operator !=(global::Omnius.Lxna.Components.Internal.Models.FileMeta? left, global::Omnius.Lxna.Components.Internal.Models.FileMeta? right)
        {
            return !(left == right);
        }
        public override bool Equals(object? other)
        {
            if (!(other is global::Omnius.Lxna.Components.Internal.Models.FileMeta)) return false;
            return this.Equals((global::Omnius.Lxna.Components.Internal.Models.FileMeta)other);
        }
        public bool Equals(global::Omnius.Lxna.Components.Internal.Models.FileMeta? target)
        {
            if (target is null) return false;
            if (object.ReferenceEquals(this, target)) return true;
            if (this.Path != target.Path) return false;
            if (this.Length != target.Length) return false;
            if (this.LastWriteTime != target.LastWriteTime) return false;

            return true;
        }
        public override int GetHashCode() => ___hashCode.Value;

        private sealed class ___CustomFormatter : global::Omnius.Core.RocketPack.IRocketPackObjectFormatter<global::Omnius.Lxna.Components.Internal.Models.FileMeta>
        {
            public void Serialize(ref global::Omnius.Core.RocketPack.RocketPackObjectWriter w, in global::Omnius.Lxna.Components.Internal.Models.FileMeta value, in int rank)
            {
                if (rank > 256) throw new global::System.FormatException();

                if (value.Path != global::Omnius.Lxna.Components.Models.NestedPath.Empty)
                {
                    w.Write((uint)1);
                    global::Omnius.Lxna.Components.Models.NestedPath.Formatter.Serialize(ref w, value.Path, rank + 1);
                }
                if (value.Length != 0)
                {
                    w.Write((uint)2);
                    w.Write(value.Length);
                }
                if (value.LastWriteTime != global::Omnius.Core.RocketPack.Timestamp.Zero)
                {
                    w.Write((uint)3);
                    w.Write(value.LastWriteTime);
                }
                w.Write((uint)0);
            }
            public global::Omnius.Lxna.Components.Internal.Models.FileMeta Deserialize(ref global::Omnius.Core.RocketPack.RocketPackObjectReader r, in int rank)
            {
                if (rank > 256) throw new global::System.FormatException();

                global::Omnius.Lxna.Components.Models.NestedPath p_path = global::Omnius.Lxna.Components.Models.NestedPath.Empty;
                ulong p_length = 0;
                global::Omnius.Core.RocketPack.Timestamp p_lastWriteTime = global::Omnius.Core.RocketPack.Timestamp.Zero;

                for (; ; )
                {
                    uint id = r.GetUInt32();
                    if (id == 0) break;
                    switch (id)
                    {
                        case 1:
                            {
                                p_path = global::Omnius.Lxna.Components.Models.NestedPath.Formatter.Deserialize(ref r, rank + 1);
                                break;
                            }
                        case 2:
                            {
                                p_length = r.GetUInt64();
                                break;
                            }
                        case 3:
                            {
                                p_lastWriteTime = r.GetTimestamp();
                                break;
                            }
                    }
                }

                return new global::Omnius.Lxna.Components.Internal.Models.FileMeta(p_path, p_length, p_lastWriteTime);
            }
        }
    }
    internal sealed partial class ThumbnailMeta : global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta>
    {
        public static global::Omnius.Core.RocketPack.IRocketPackObjectFormatter<global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta> Formatter => global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta>.Formatter;
        public static global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta Empty => global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta>.Empty;

        static ThumbnailMeta()
        {
            global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta>.Formatter = new ___CustomFormatter();
            global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta>.Empty = new global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta((global::Omnius.Lxna.Components.Models.ThumbnailResizeType)0, (global::Omnius.Lxna.Components.Models.ThumbnailFormatType)0, 0, 0);
        }

        private readonly global::System.Lazy<int> ___hashCode;

        public ThumbnailMeta(global::Omnius.Lxna.Components.Models.ThumbnailResizeType resizeType, global::Omnius.Lxna.Components.Models.ThumbnailFormatType formatType, uint width, uint height)
        {
            this.ResizeType = resizeType;
            this.FormatType = formatType;
            this.Width = width;
            this.Height = height;

            ___hashCode = new global::System.Lazy<int>(() =>
            {
                var ___h = new global::System.HashCode();
                if (resizeType != default) ___h.Add(resizeType.GetHashCode());
                if (formatType != default) ___h.Add(formatType.GetHashCode());
                if (width != default) ___h.Add(width.GetHashCode());
                if (height != default) ___h.Add(height.GetHashCode());
                return ___h.ToHashCode();
            });
        }

        public global::Omnius.Lxna.Components.Models.ThumbnailResizeType ResizeType { get; }
        public global::Omnius.Lxna.Components.Models.ThumbnailFormatType FormatType { get; }
        public uint Width { get; }
        public uint Height { get; }

        public static global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta Import(global::System.Buffers.ReadOnlySequence<byte> sequence, global::Omnius.Core.IBytesPool bytesPool)
        {
            var reader = new global::Omnius.Core.RocketPack.RocketPackObjectReader(sequence, bytesPool);
            return Formatter.Deserialize(ref reader, 0);
        }
        public void Export(global::System.Buffers.IBufferWriter<byte> bufferWriter, global::Omnius.Core.IBytesPool bytesPool)
        {
            var writer = new global::Omnius.Core.RocketPack.RocketPackObjectWriter(bufferWriter, bytesPool);
            Formatter.Serialize(ref writer, this, 0);
        }

        public static bool operator ==(global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta? left, global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta? right)
        {
            return (right is null) ? (left is null) : right.Equals(left);
        }
        public static bool operator !=(global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta? left, global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta? right)
        {
            return !(left == right);
        }
        public override bool Equals(object? other)
        {
            if (!(other is global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta)) return false;
            return this.Equals((global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta)other);
        }
        public bool Equals(global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta? target)
        {
            if (target is null) return false;
            if (object.ReferenceEquals(this, target)) return true;
            if (this.ResizeType != target.ResizeType) return false;
            if (this.FormatType != target.FormatType) return false;
            if (this.Width != target.Width) return false;
            if (this.Height != target.Height) return false;

            return true;
        }
        public override int GetHashCode() => ___hashCode.Value;

        private sealed class ___CustomFormatter : global::Omnius.Core.RocketPack.IRocketPackObjectFormatter<global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta>
        {
            public void Serialize(ref global::Omnius.Core.RocketPack.RocketPackObjectWriter w, in global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta value, in int rank)
            {
                if (rank > 256) throw new global::System.FormatException();

                if (value.ResizeType != (global::Omnius.Lxna.Components.Models.ThumbnailResizeType)0)
                {
                    w.Write((uint)1);
                    w.Write((ulong)value.ResizeType);
                }
                if (value.FormatType != (global::Omnius.Lxna.Components.Models.ThumbnailFormatType)0)
                {
                    w.Write((uint)2);
                    w.Write((ulong)value.FormatType);
                }
                if (value.Width != 0)
                {
                    w.Write((uint)3);
                    w.Write(value.Width);
                }
                if (value.Height != 0)
                {
                    w.Write((uint)4);
                    w.Write(value.Height);
                }
                w.Write((uint)0);
            }
            public global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta Deserialize(ref global::Omnius.Core.RocketPack.RocketPackObjectReader r, in int rank)
            {
                if (rank > 256) throw new global::System.FormatException();

                global::Omnius.Lxna.Components.Models.ThumbnailResizeType p_resizeType = (global::Omnius.Lxna.Components.Models.ThumbnailResizeType)0;
                global::Omnius.Lxna.Components.Models.ThumbnailFormatType p_formatType = (global::Omnius.Lxna.Components.Models.ThumbnailFormatType)0;
                uint p_width = 0;
                uint p_height = 0;

                for (; ; )
                {
                    uint id = r.GetUInt32();
                    if (id == 0) break;
                    switch (id)
                    {
                        case 1:
                            {
                                p_resizeType = (global::Omnius.Lxna.Components.Models.ThumbnailResizeType)r.GetUInt64();
                                break;
                            }
                        case 2:
                            {
                                p_formatType = (global::Omnius.Lxna.Components.Models.ThumbnailFormatType)r.GetUInt64();
                                break;
                            }
                        case 3:
                            {
                                p_width = r.GetUInt32();
                                break;
                            }
                        case 4:
                            {
                                p_height = r.GetUInt32();
                                break;
                            }
                    }
                }

                return new global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta(p_resizeType, p_formatType, p_width, p_height);
            }
        }
    }
    internal sealed partial class ThumbnailCache : global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Lxna.Components.Internal.Models.ThumbnailCache>
    {
        public static global::Omnius.Core.RocketPack.IRocketPackObjectFormatter<global::Omnius.Lxna.Components.Internal.Models.ThumbnailCache> Formatter => global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Lxna.Components.Internal.Models.ThumbnailCache>.Formatter;
        public static global::Omnius.Lxna.Components.Internal.Models.ThumbnailCache Empty => global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Lxna.Components.Internal.Models.ThumbnailCache>.Empty;

        static ThumbnailCache()
        {
            global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Lxna.Components.Internal.Models.ThumbnailCache>.Formatter = new ___CustomFormatter();
            global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Lxna.Components.Internal.Models.ThumbnailCache>.Empty = new global::Omnius.Lxna.Components.Internal.Models.ThumbnailCache(global::Omnius.Lxna.Components.Internal.Models.FileMeta.Empty, global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta.Empty, global::System.Array.Empty<global::Omnius.Lxna.Components.Models.ThumbnailContent>());
        }

        private readonly global::System.Lazy<int> ___hashCode;

        public static readonly int MaxContentsCount = 8192;

        public ThumbnailCache(global::Omnius.Lxna.Components.Internal.Models.FileMeta fileMeta, global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta thumbnailMeta, global::Omnius.Lxna.Components.Models.ThumbnailContent[] contents)
        {
            if (fileMeta is null) throw new global::System.ArgumentNullException("fileMeta");
            if (thumbnailMeta is null) throw new global::System.ArgumentNullException("thumbnailMeta");
            if (contents is null) throw new global::System.ArgumentNullException("contents");
            if (contents.Length > 8192) throw new global::System.ArgumentOutOfRangeException("contents");
            foreach (var n in contents)
            {
                if (n is null) throw new global::System.ArgumentNullException("n");
            }

            this.FileMeta = fileMeta;
            this.ThumbnailMeta = thumbnailMeta;
            this.Contents = new global::Omnius.Core.Collections.ReadOnlyListSlim<global::Omnius.Lxna.Components.Models.ThumbnailContent>(contents);

            ___hashCode = new global::System.Lazy<int>(() =>
            {
                var ___h = new global::System.HashCode();
                if (fileMeta != default) ___h.Add(fileMeta.GetHashCode());
                if (thumbnailMeta != default) ___h.Add(thumbnailMeta.GetHashCode());
                foreach (var n in contents)
                {
                    if (n != default) ___h.Add(n.GetHashCode());
                }
                return ___h.ToHashCode();
            });
        }

        public global::Omnius.Lxna.Components.Internal.Models.FileMeta FileMeta { get; }
        public global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta ThumbnailMeta { get; }
        public global::Omnius.Core.Collections.ReadOnlyListSlim<global::Omnius.Lxna.Components.Models.ThumbnailContent> Contents { get; }

        public static global::Omnius.Lxna.Components.Internal.Models.ThumbnailCache Import(global::System.Buffers.ReadOnlySequence<byte> sequence, global::Omnius.Core.IBytesPool bytesPool)
        {
            var reader = new global::Omnius.Core.RocketPack.RocketPackObjectReader(sequence, bytesPool);
            return Formatter.Deserialize(ref reader, 0);
        }
        public void Export(global::System.Buffers.IBufferWriter<byte> bufferWriter, global::Omnius.Core.IBytesPool bytesPool)
        {
            var writer = new global::Omnius.Core.RocketPack.RocketPackObjectWriter(bufferWriter, bytesPool);
            Formatter.Serialize(ref writer, this, 0);
        }

        public static bool operator ==(global::Omnius.Lxna.Components.Internal.Models.ThumbnailCache? left, global::Omnius.Lxna.Components.Internal.Models.ThumbnailCache? right)
        {
            return (right is null) ? (left is null) : right.Equals(left);
        }
        public static bool operator !=(global::Omnius.Lxna.Components.Internal.Models.ThumbnailCache? left, global::Omnius.Lxna.Components.Internal.Models.ThumbnailCache? right)
        {
            return !(left == right);
        }
        public override bool Equals(object? other)
        {
            if (!(other is global::Omnius.Lxna.Components.Internal.Models.ThumbnailCache)) return false;
            return this.Equals((global::Omnius.Lxna.Components.Internal.Models.ThumbnailCache)other);
        }
        public bool Equals(global::Omnius.Lxna.Components.Internal.Models.ThumbnailCache? target)
        {
            if (target is null) return false;
            if (object.ReferenceEquals(this, target)) return true;
            if (this.FileMeta != target.FileMeta) return false;
            if (this.ThumbnailMeta != target.ThumbnailMeta) return false;
            if (!global::Omnius.Core.Helpers.CollectionHelper.Equals(this.Contents, target.Contents)) return false;

            return true;
        }
        public override int GetHashCode() => ___hashCode.Value;

        private sealed class ___CustomFormatter : global::Omnius.Core.RocketPack.IRocketPackObjectFormatter<global::Omnius.Lxna.Components.Internal.Models.ThumbnailCache>
        {
            public void Serialize(ref global::Omnius.Core.RocketPack.RocketPackObjectWriter w, in global::Omnius.Lxna.Components.Internal.Models.ThumbnailCache value, in int rank)
            {
                if (rank > 256) throw new global::System.FormatException();

                if (value.FileMeta != global::Omnius.Lxna.Components.Internal.Models.FileMeta.Empty)
                {
                    w.Write((uint)1);
                    global::Omnius.Lxna.Components.Internal.Models.FileMeta.Formatter.Serialize(ref w, value.FileMeta, rank + 1);
                }
                if (value.ThumbnailMeta != global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta.Empty)
                {
                    w.Write((uint)2);
                    global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta.Formatter.Serialize(ref w, value.ThumbnailMeta, rank + 1);
                }
                if (value.Contents.Count != 0)
                {
                    w.Write((uint)3);
                    w.Write((uint)value.Contents.Count);
                    foreach (var n in value.Contents)
                    {
                        global::Omnius.Lxna.Components.Models.ThumbnailContent.Formatter.Serialize(ref w, n, rank + 1);
                    }
                }
                w.Write((uint)0);
            }
            public global::Omnius.Lxna.Components.Internal.Models.ThumbnailCache Deserialize(ref global::Omnius.Core.RocketPack.RocketPackObjectReader r, in int rank)
            {
                if (rank > 256) throw new global::System.FormatException();

                global::Omnius.Lxna.Components.Internal.Models.FileMeta p_fileMeta = global::Omnius.Lxna.Components.Internal.Models.FileMeta.Empty;
                global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta p_thumbnailMeta = global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta.Empty;
                global::Omnius.Lxna.Components.Models.ThumbnailContent[] p_contents = global::System.Array.Empty<global::Omnius.Lxna.Components.Models.ThumbnailContent>();

                for (; ; )
                {
                    uint id = r.GetUInt32();
                    if (id == 0) break;
                    switch (id)
                    {
                        case 1:
                            {
                                p_fileMeta = global::Omnius.Lxna.Components.Internal.Models.FileMeta.Formatter.Deserialize(ref r, rank + 1);
                                break;
                            }
                        case 2:
                            {
                                p_thumbnailMeta = global::Omnius.Lxna.Components.Internal.Models.ThumbnailMeta.Formatter.Deserialize(ref r, rank + 1);
                                break;
                            }
                        case 3:
                            {
                                var length = r.GetUInt32();
                                p_contents = new global::Omnius.Lxna.Components.Models.ThumbnailContent[length];
                                for (int i = 0; i < p_contents.Length; i++)
                                {
                                    p_contents[i] = global::Omnius.Lxna.Components.Models.ThumbnailContent.Formatter.Deserialize(ref r, rank + 1);
                                }
                                break;
                            }
                    }
                }

                return new global::Omnius.Lxna.Components.Internal.Models.ThumbnailCache(p_fileMeta, p_thumbnailMeta, p_contents);
            }
        }
    }
}
