// <auto-generated/>
#nullable enable

namespace Omnius.Lxna.Components.Image;

public enum ImageResizeType : byte
{
    Unknown = 0,
    Crop = 1,
    Pad = 2,
    BoxPad = 3,
    Max = 4,
    Min = 5,
}
public enum ImageResizePositionType : byte
{
    Unknown = 0,
    Center = 1,
}
public enum ImageResizeResamplerType : byte
{
    Unknown = 0,
    Lanczos3 = 1,
}
public enum ImageFormatType : byte
{
    Unknown = 0,
    Png = 1,
}
