// <auto-generated/>
#nullable enable

namespace Omnius.Lxna.Components.Image;

public enum ImageResizeType : byte
{
    Pad = 0,
    Crop = 1,
}
public enum ImageResizePositionType : byte
{
    Center = 0,
}
public enum ImageResizeResamplerType : byte
{
    Lanczos3 = 0,
}
public enum ImageFormatType : byte
{
    Png = 0,
}
