- Includes:
    - ./refs/core/rpfs/**/*.rpf
    - ./rpfs/**/*.rpf
  CompileTargets:
    - Input: ./rpfs/Omnius.Lxna.Components/Omnius.Lxna.Components.Storages.Models.rpf
      Output: ./src/Omnius.Lxna.Components/Storages/Models/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Lxna.Components/Omnius.Lxna.Components.Thumbnails.Models.rpf
      Output: ./src/Omnius.Lxna.Components/Thumbnails/Models/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Lxna.Components/Omnius.Lxna.Components.Thumbnails.Internal.Common.Models.rpf
      Output: ./src/Omnius.Lxna.Components/Thumbnails/implementations/Internal/Common/Models/_RocketPack/_Generated.cs
