- Includes:
    - ./refs/core/rpfs/**/*.rpf
    - ./rpfs/**/*.rpf
  CompileTargets:
    - Input: ./rpfs/Omnius.Lxna.Components/Omnius.Lxna.Components.Storages.rpf
      Output: ./src/Omnius.Lxna.Components/Storages/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Lxna.Components/Omnius.Lxna.Components.ThumbnailGenerators.rpf
      Output: ./src/Omnius.Lxna.Components/ThumbnailGenerators/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Lxna.Components/Omnius.Lxna.Components.ThumbnailGenerators.Internal.rpf
      Output: ./src/Omnius.Lxna.Components/ThumbnailGenerators/Internal/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Lxna.Components/Omnius.Lxna.Components.IconGenerators.rpf
      Output: ./src/Omnius.Lxna.Components/IconGenerators/_RocketPack/_Generated.cs
