// <auto-generated/>
#nullable enable
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace Omnius.Lxna.Ui.Desktop.Configuration
{
    public sealed partial class UiState : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;

        private void RaisePropertyChanged([CallerMemberName] string? propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        private int _thumbnail_Width;

        public int Thumbnail_Width
        {
            get => _thumbnail_Width;
            set
            {
                if (!_thumbnail_Width.Equals(value))
                {
                    _thumbnail_Width = value;
                    this.RaisePropertyChanged(nameof(Thumbnail_Width));
                }
            }
        }
        private int _thumbnail_Height;

        public int Thumbnail_Height
        {
            get => _thumbnail_Height;
            set
            {
                if (!_thumbnail_Height.Equals(value))
                {
                    _thumbnail_Height = value;
                    this.RaisePropertyChanged(nameof(Thumbnail_Height));
                }
            }
        }
        private double _fileView_TreeViewWidth;

        public double FileView_TreeViewWidth
        {
            get => _fileView_TreeViewWidth;
            set
            {
                if (!_fileView_TreeViewWidth.Equals(value))
                {
                    _fileView_TreeViewWidth = value;
                    this.RaisePropertyChanged(nameof(FileView_TreeViewWidth));
                }
            }
        }
    }
}
