name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      ContinuousIntegrationBuild: true
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
      - name: Setup dotnet tool
        run: dotnet tool restore
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: bash build-linux.sh
      - name: Zip
        run: |
          cd ./pub/linux-x64 && zip -r ../../lxna-linux-x64-${{ env.RELEASE_VERSION }}.zip ./*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            lxna-linux-x64-${{ env.RELEASE_VERSION }}.zip
  windows:
    runs-on: windows-latest
    env:
      ContinuousIntegrationBuild: true
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Set env
        run: |
          chcp 65001 #set code page to utf-8
          echo ("RELEASE_VERSION=" + $env:GITHUB_REF.replace('refs/tags/', '')) >> $env:GITHUB_ENV
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
      - name: Setup dotnet tool
        run: dotnet tool restore
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: pwsh build-win.ps1
      - name: Zip
        uses: vimtor/action-zip@v1
        with:
          files: ./pub/win-x64
          dest: lxna-win-x64-${{ env.RELEASE_VERSION }}.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            lxna-win-x64-${{ env.RELEASE_VERSION }}.zip
