name: update

on:
  schedule:
    - cron: "0 12 * * 0"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100-preview.8.20417.9
      - name: Update
        run: make update
      - name: Create Pull-Request
        uses: peter-evans/create-pull-request@v2
        with:
          title: Update into develop.
          branch: update
          token: ${{ secrets.GITHUB_TOKEN }}
